# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Luis Valle
tagline:          'Luis technical blog'
description:      'Android bot @ <a href="http://bizzby.com" target="_blank">BIZZBY</a>.'
url:              http://lgvalle.github.io/
baseurl:          http://lgvalle.github.io/

author:
  name:           'Luis G. Valle'
  twitter:        https://twitter.com/lgvalle
  gplus:          https://plus.google.com/+LuisGonzálezValle

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lgvalle
